CREATE TABLE assigned_task (
                               idAssigned BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               idTask    BIGINT NOT NULL,
                               idUser    BIGINT NOT NULL,
                               isDone    BOOLEAN NOT NULL
);


CREATE TABLE categories (
                            id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE items (
                       id_item          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       expiration_date  DATE    NOT NULL,
                       product_id       BIGINT  NOT NULL
);
CREATE TABLE location_of_items (
                                   idLocation BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   idItem     BIGINT,
                                   idShelves  BIGINT
);
CREATE TABLE products (
                          id_product   BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name_product VARCHAR(200) NOT NULL,
                          category_id  BIGINT   NOT NULL
);
CREATE TABLE shelves (
                          idShelves   BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description VARCHAR(200) NOT NULL
);
CREATE TABLE tasks (
                       idTask       BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       description  VARCHAR(200) NOT NULL,
                       shelf_from_id BIGINT  ,
                       shelf_to_id   BIGINT   ,
                       product_id    BIGINT
);
CREATE TABLE users (
                       idUser   BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(200) NOT NULL UNIQUE,
                       password VARCHAR(200) NOT NULL,
                       is_admin BOOLEAN NOT NULL
);
